### ISSUE TITLE
Document plugin protocol

### ISSUE THREAD

**Issue by squaremo** [ClusterHQ/docker-plugins#2]
We should consolidate (and bring up to date) any plugin protocol documentation and put it in this repo.

**Comment by progrium** [comment]
Perhaps in the wiki as to avoid it getting lost somewhere in some branch.

On Fri, Apr 10, 2015 at 8:41 AM, Michael Bridgen notifications@github.com
wrote:

> We should consolidate (and bring up to date) any plugin protocol
> documentation and put it in this repo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ClusterHQ/docker-plugins/issues/2.

## 

Jeff Lindsay
http://progrium.com

**Comment by squaremo** [comment]
https://github.com/ClusterHQ/docker-plugins/wiki/PluginProtocol

**Comment by squaremo** [comment]
It's not fully documented but it's a start
